package com.reajason.javaweb.probe.config;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.reajason.javaweb.probe.ProbeContent;
import com.reajason.javaweb.probe.ProbeMethod;
import com.reajason.javaweb.utils.CommonUtil;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import net.bytebuddy.jar.asm.Opcodes;

/**
 * @author ReaJason
 * @since 2025/6/30
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ProbeConfig {
    @JsonPropertyDescription("Probe (echo) method: DNSLog, ResponseBody or Sleep")
    private ProbeMethod probeMethod;

    @JsonPropertyDescription("What to echo back: Server, OS, JDK, Bytecode, Command, BasicInfo, ScriptEngine or Filter")
    private ProbeContent probeContent;

    @JsonProperty(required = false)
    @JsonPropertyDescription("Probe shell class name; random by default")
    @Builder.Default
    private String shellClassName = CommonUtil.generateInjectorClassName();
    /**
     * 生成类的目标 JRE 版本
     */
    @JsonProperty(required = false)
    @JsonPropertyDescription("Target JRE class file version: 50 = Java 6, 52 = Java 8, 61 = Java 17. Defaults to 50")
    @Builder.Default
    private int targetJreVersion = Opcodes.V1_6;

    /**
     * 是否需要移除模块限制
     */
    @JsonProperty(required = false)
    @JsonPropertyDescription("Bypass Java module restrictions; auto-enabled when targetJreVersion >= 53 (Java 9)")
    @Builder.Default
    private boolean byPassJavaModule = false;

    /**
     * 是否开启调试
     */
    @JsonProperty(required = false)
    @JsonPropertyDescription("Print debug info to target server logs")
    @Builder.Default
    private boolean debug = false;

    /**
     * 是否启用缩小字节码
     */
    @JsonProperty(required = false)
    @JsonPropertyDescription("Shrink the generated bytecode")
    @Builder.Default
    private boolean shrink = false;

    /**
     * 是否添加静态代码块调用构造方法
     */
    @JsonProperty(required = false)
    @JsonPropertyDescription("Add a static initializer block that calls the constructor")
    @Builder.Default
    private boolean staticInitialize = false;

    /**
     * 追加 Lambda 类名后缀
     */
    @JsonProperty(required = false)
    @JsonPropertyDescription("Append a lambda-style suffix to generated class names")
    @Builder.Default
    private boolean lambdaSuffix = false;

    public boolean isDebugOff() {
        return !debug;
    }

    public boolean needByPassJavaModule() {
        return byPassJavaModule || targetJreVersion >= Opcodes.V9;
    }
}
