package com.reajason.javaweb.memshell.config;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.reajason.javaweb.memshell.ShellType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import net.bytebuddy.jar.asm.Opcodes;

/**
 * @author ReaJason
 * @since 2024/12/6
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ShellConfig {
    /**
     * 目标服务类型
     */
    @JsonPropertyDescription("Target server type, e.g. Tomcat, Jetty, SpringWebMVC, WebLogic; see memshell_capabilities for valid values")
    private String server;

    /**
     * 目标服务版本
     */
    @JsonProperty(required = false)
    @JsonPropertyDescription("Target server version, e.g. 10.1. Defaults to unknown")
    @Builder.Default
    private String serverVersion = "unknown";

    /**
     * 内存马功能
     */
    @JsonPropertyDescription("Shell tool: Godzilla, Behinder, Command, Suo5, Suo5v2, AntSword, NeoreGeorg, Proxy or Custom")
    private String shellTool;

    /**
     * 内存马类型
     */
    @JsonPropertyDescription("Shell (injector) type, e.g. Filter, Listener, Servlet, Agent; valid values depend on server and shellTool, see memshell_capabilities")
    private String shellType;

    /**
     * 生成类的目标 JRE 版本
     */
    @JsonProperty(required = false)
    @JsonPropertyDescription("Target JRE class file version: 50 = Java 6, 52 = Java 8, 61 = Java 17. Defaults to 50")
    @Builder.Default
    private int targetJreVersion = Opcodes.V1_6;

    /**
     * 是否需要移除模块限制
     */
    @JsonProperty(required = false)
    @JsonPropertyDescription("Bypass Java module restrictions; auto-enabled when targetJreVersion >= 53 (Java 9)")
    @Builder.Default
    private boolean byPassJavaModule = false;

    /**
     * 是否开启调试
     */
    @JsonProperty(required = false)
    @JsonPropertyDescription("Print debug info to target server logs")
    @Builder.Default
    private boolean debug = false;

    /**
     * 是否使用回显模式
     */
    @JsonProperty(required = false)
    @JsonPropertyDescription("Enable probe (echo) mode")
    @Builder.Default
    private boolean probe = false;

    /**
     * 是否启用缩小字节码
     */
    @JsonProperty(required = false)
    @JsonPropertyDescription("Shrink the generated bytecode")
    @Builder.Default
    private boolean shrink = false;

    /**
     * 追加 Lambda 类名后缀
     */
    @JsonProperty(required = false)
    @JsonPropertyDescription("Append a lambda-style suffix to generated class names")
    @Builder.Default
    private boolean lambdaSuffix = false;

    /**
     * 将 Java EE 转换为 Jakarta EE 类名
     */
    @JsonProperty(required = false)
    @JsonPropertyDescription("Use Jakarta EE class names instead of Java EE; auto-enabled for Jakarta* shell types")
    @Builder.Default
    private boolean jakarta = false;

    public boolean isDebugOff() {
        return !debug;
    }

    public boolean isJakarta() {
        return jakarta || shellType.startsWith(ShellType.JAKARTA);
    }

    public boolean needByPassJavaModule() {
        return byPassJavaModule || targetJreVersion >= Opcodes.V9;
    }
}
