import { describe, expect, it } from "vitest";

import {
  aesEcbDecrypt,
  aesEcbEncrypt,
  base64UrlDecode,
  base64UrlEncode,
  gunzipLenient,
  gzip,
  md5Hex,
  md5Key16,
  randomString,
} from "./crypto.js";

describe("md5", () => {
  it("matches the hex values baked into real shells", () => {
    // verified against shells generated by MemShellParty (godzilla pass/key = pass/key)
    expect(md5Key16("key")).toBe("3c6e0b8a9c15224a");
    expect(md5Key16("rebeyond")).toBe("e45e329feb5d925b");
    expect(md5Hex("pass3c6e0b8a9c15224a").toUpperCase()).toBe("11CD6A87589841636C37AC826A2A04BC");
  });
});

describe("aes-ecb", () => {
  it("encrypts exactly like Java AES/ECB/PKCS5Padding (openssl vector)", () => {
    const encrypted = aesEcbEncrypt(Buffer.from("hello memshell1234", "utf8"), "3c6e0b8a9c15224a");
    expect(encrypted.toString("hex")).toBe(
      "325b7465bea6f294db413b54142d7957492266f19adda6285c62fc77255928d4",
    );
  });

  it("round-trips arbitrary data", () => {
    const data = Buffer.alloc(100, 7);
    const key = md5Key16("whatever");
    expect(aesEcbDecrypt(aesEcbEncrypt(data, key), key)).toEqual(data);
  });

  it("throws on a wrong key (bad padding)", () => {
    const encrypted = aesEcbEncrypt(Buffer.from("secret"), "3c6e0b8a9c15224a");
    expect(() => aesEcbDecrypt(encrypted, "e45e329feb5d925b")).toThrow();
  });
});

describe("gzip helpers", () => {
  it("round-trips", () => {
    const data = Buffer.from("godzilla method params");
    expect(gunzipLenient(gzip(data))).toEqual(data);
  });

  it("gunzipLenient returns small raw inputs untouched (godzilla gzipD behaviour)", () => {
    const raw = Buffer.from("ok");
    expect(gunzipLenient(raw)).toEqual(raw);
  });
});

describe("base64url", () => {
  it("round-trips without padding", () => {
    const data = Buffer.from([0xfb, 0xff, 0xfe, 0x01, 0x02]);
    const encoded = base64UrlEncode(data);
    expect(encoded).not.toMatch(/[+/=]/);
    expect(base64UrlDecode(encoded)).toEqual(data);
  });

  it("decodes padded and unpadded input", () => {
    expect(base64UrlDecode("-__-AQI")).toEqual(Buffer.from([0xfb, 0xff, 0xfe, 0x01, 0x02]));
  });
});

describe("randomString", () => {
  it("produces alphanumeric strings of the requested length", () => {
    const s = randomString(64);
    expect(s).toMatch(/^[A-Za-z0-9]{64}$/);
    expect(randomString(0)).toBe("");
  });
});
