services:
  tomcat56:
    image: reajason/tomcat:5-jdk6
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    volumes:
      - /Users/reajason/workspace/arthas:/usr/local/arthas
      - ../../../vul/vul-webapp/build/libs/vul-webapp.war:/usr/local/tomcat/webapps/app.war