services:
  weblogic14110:
    image: reajason/weblogic:14.1.1.0
    container_name: weblogic14110
    ports:
      - "7001:7001"
      - "5005:5005"
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n"
    volumes:
      - ../../../vul/vul-webapp/build/libs/vul-webapp.war:/u01/oracle/user_projects/domains/domain1/autodeploy/app.war