name: docker-push
on:
  workflow_dispatch:
    inputs:
      path:
        description: 'Path'
        required: true
        default: '/redqueen-memshell-party'
      tag:
        description: "Tag"
        required: true
        default: "redqueen"
jobs:
  docker-push:
    name: Docker Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push RedQueen
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            ROUTE_ROOT_PATH=${{ inputs.path }}
            CONTEXT_PATH=${{ inputs.path }}
          push: true
          tags: |
            docker.io/reajason/memshell-party:${{ inputs.tag }}
